name: 'checkin every day'

on:
  workflow_dispatch:
    inputs:
      actions:
        description: "action: start"
        default: "start"
  schedule:
    - cron: '1 16 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Print secrets
        run: echo ${{ secrets.HEATH_URL }} ${{ secrets.HEATH_BODY }}
      - name: Test maven
        run: mvn -Durl=${{ secrets.HEATH_URL }} -Dbody=${{ secrets.HEATH_BODY }} test
