name: 'checkin every day'

on:
  workflow_dispatch:
    inputs:
      actions:
        description: "action: start"
        default: "start"
  schedule:
    - cron: '1 08 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '1.8'
          distribution: 'jdk'
      - name: Test maven
        run: mvn -Durl=${{secrets.HEATH_URL}} -Dbody=${{secrets.HEATH_BODY}} test